flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- async-2.1.0
- attoparsec-0.13.0.2
- blaze-builder-0.4.0.2
- conduit-1.2.7
- conduit-extra-1.1.13.2
- exceptions-0.8.3
- hashable-1.2.4.0
- lifted-base-0.2.3.8
- mmorph-1.0.6
- monad-control-1.0.1.0
- mtl-2.2.1
- network-2.6.3.1
- primitive-0.6.1.0
- random-1.1
- resourcet-1.1.7.5
- scientific-0.3.4.9
- stm-2.4.4.1
- streaming-commons-0.1.15.5
- text-1.2.2.1
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- vector-0.11.0.0
- zlib-0.6.1.1
resolver: ghc-8.0.1
