flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- async-2.1.0
- attoparsec-0.13.0.2
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- cereal-0.5.3.0
- cereal-conduit-0.7.3
- chunked-data-0.3.0
- conduit-1.2.7
- conduit-combinators-1.0.4
- conduit-extra-1.1.13.2
- constraints-0.8
- exceptions-0.8.3
- hashable-1.2.4.0
- lifted-async-0.9.0
- lifted-base-0.2.3.8
- mmorph-1.0.6
- monad-control-1.0.1.0
- monad-loops-0.4.3
- mono-traversable-1.0.0.1
- mtl-2.2.1
- mwc-random-0.13.4.0
- network-2.6.3.1
- primitive-0.6.1.0
- random-1.1
- resourcet-1.1.7.5
- scientific-0.3.4.9
- semigroups-0.18.2
- split-0.2.3.1
- stm-2.4.4.1
- stm-chans-3.0.0.4
- stm-conduit-3.0.0
- streaming-commons-0.1.15.5
- text-1.2.2.1
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.2.0
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- void-0.7.1
- zlib-0.6.1.1
resolver: ghc-8.0.1
